version: "3"

services:
  app:
    image: ouuan/plausible-visitor-count
    restart: always
    ports:
      - 3000:3000
    environment:
      PLAUSIBLE_URL: https://plausible.io
      PLAUSIBLE_SITE_ID: example.com
      PLAUSIBLE_API_KEY: generate an API key on Plausible
